version: "3.2"
services:
  app:
    container_name: pj3_server 
    restart: always 
    build: ./nodejs
    ports:
      - "40000:8080"
    links:
      - mongo 
  mongo:
    container_name: mongo 
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"
