version: "2"
services:
  app:
    container_name: pj3_server 
    restart: "on-failure" 
    build: ./nodejs
    ports:
      - "40000:3000"
    links:
      - mongo 
  mongo:
    container_name: mongo 
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
